<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="O’Neal Gray, David Laurel" />

<meta name="date" content="2023-03-01" />

<title>Beers And Breweries</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="BeersAndBreweries.html">Beers and Breweries</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Beers And Breweries</h1>
<h4 class="author">O’Neal Gray, David Laurel</h4>
<h4 class="date">2023-03-01</h4>

</div>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Dear CEO and CFO of Budweiser,</p>
<p>We are pleased to present the results of our analysis of the data you
provided. Our objective was to gain a deeper understanding of the
relationship between alcohol by volume (ABV) and various other factors,
such as the number of breweries in each state, the bitterness of beer,
and the correlation between bitterness and alcohol content.</p>
<p>In conducting our analysis, we utilized various statistical tools and
techniques, including scatter plots, bar charts, and KNN classifiers.
Our findings have uncovered several interesting insights that we believe
will be of great value to Budweiser.</p>
<p>Please find below a summary of our key findings. If you have any
questions or comments, we would be happy to discuss them further. Our
aim is to provide you with results that are clear, concise, and
actionable.</p>
</div>
<div id="breweries-by-state" class="section level2">
<h2>Breweries by State</h2>
<p>The data set contained 558 breweries across the United States, with
the top five states accounting for 31% of the total (175 breweries). The
states were ranked in order of largest to smallest, with Colorado being
the largest with 8.42% of the total, followed by California (6.99% of
the total), Michigan (5.73% of the total), Oregon (5.20% of the total),
and Texas (5.02% of the total)</p>
<p><img src="BeersAndBreweries_files/figure-html/plot_breweries_by_state-1.png" width="672" /></p>
</div>
<div id="missing-values" class="section level2">
<h2>Missing Values</h2>
<p>Several values were missing for both the ABV and IBU columns. We
needed to make sure that we were approaching these missing values in the
correct way. First we determined that these were Missing-At-Random. Then
we determined that the proportion of missing rows to total was somewhat
significant at 41.7%. Unfortunately, this high number means some of our
predictions using IBU may be slightly skewed towards the mean.</p>
<p>At this point, to deal with the missing values, we used an algorithm
known as multivariate imputation by chaining predictive means equations.
This method works by predicting missing values using the average value
and basing this on surrounding factors that are known (e.g. predicting
missing ABV using IBU):</p>
<pre class="r"><code>summary(beer_brews[,c(&quot;ABV&quot;, &quot;IBU&quot;)])</code></pre>
<pre><code>##       ABV               IBU        
##  Min.   :0.00100   Min.   :  4.00  
##  1st Qu.:0.05000   1st Qu.: 21.00  
##  Median :0.05600   Median : 35.00  
##  Mean   :0.05977   Mean   : 42.71  
##  3rd Qu.:0.06700   3rd Qu.: 64.00  
##  Max.   :0.12800   Max.   :138.00  
##  NA&#39;s   :62        NA&#39;s   :1005</code></pre>
<pre class="r"><code>(nrow(beer_brews[!complete.cases(beer_brews),]) / nrow(beer_brews)) * 100.0 # percentage of rows that are missing from the data</code></pre>
<pre><code>## [1] 41.70124</code></pre>
<pre class="r"><code>cor(beer_brews$ABV, beer_brews$IBU, use = &quot;complete.obs&quot;) # 0.67 correlation between ABV and IBU, good predictor for multi-imputation, &quot;mice&quot;</code></pre>
<pre><code>## [1] 0.6706215</code></pre>
<pre class="r"><code>summary(beer_brew_whole[,c(&quot;ABV&quot;, &quot;IBU&quot;)])</code></pre>
<pre><code>##       ABV               IBU       
##  Min.   :0.00100   Min.   :  4.0  
##  1st Qu.:0.05000   1st Qu.: 22.0  
##  Median :0.05600   Median : 35.0  
##  Mean   :0.05975   Mean   : 42.9  
##  3rd Qu.:0.06700   3rd Qu.: 64.0  
##  Max.   :0.12800   Max.   :138.0</code></pre>
</div>
<div id="median-abv-and-ibu-by-state" class="section level2">
<h2>Median ABV and IBU by State</h2>
<p>This chart presents a summary of the median Alcohol by Volume (ABV)
and International Bitterness Unit (IBU) values of beers produced in
different states across the United States. To compile the information,
the Beer and Breweries datasets were merged and the median values of ABV
and IBU were calculated for each state of production. The states with
the highest median IBU values are Montana (80 IBU), Delaware (77.5 IBU),
and Vermont (75 IBU). The states with the highest median ABV values are
Nevada (0.085), South Carolina (0.0765), Vermont (0.0715), and Kansas
(0.0715).</p>
<p><img src="BeersAndBreweries_files/figure-html/chart_abv_IBU-1.png" width="672" /></p>
</div>
<div id="highest-abv-ibu-beers" class="section level2">
<h2>Highest ABV &amp; IBU Beers</h2>
<div id="abv" class="section level3">
<h3>ABV</h3>
<p>We could pick the states which produce beers with the greatest ABV
and IBU, respectively, but it might be more interesting to determine
trends of states that are producing these high-scoring beers. To make
sure we were only picking beers with true ABV/IBU numbers, we used the
original data set without missing values imputed. From these results, we
found the states that tended to produce higher ABV beers were Colorado,
Kentucky, Indiana, New York, and Michigan.</p>
<p>From the plot below, the data appears to indicate that while Colorado
produces the single highest-ABV beer, “Lee Hill Series Vol. 5 - Belgian
Style Quadrupel Ale,” it is outpaced by Kentucky in concentration of
high-ABV beers produced:</p>
<pre class="r"><code>beer_brew_abv[order(beer_brew_abv$ABV, decreasing = TRUE )[1:6],c(&quot;Beer_Name&quot;,  &quot;State&quot;, &quot;ABV&quot;)] </code></pre>
<pre><code>##                                                Beer_Name State   ABV
## 384 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale    CO 0.128
## 9                                         London Balling    KY 0.125
## 149                                                 Csar    IN 0.120
## 387     Lee Hill Series Vol. 4 - Manhattan Style Rye Ale    CO 0.104
## 344                                               4Beans    NY 0.100
## 57                                  Wizard Burial Ground    MI 0.099</code></pre>
<pre class="r"><code>hi_abv = beer_brew_abv[beer_brew_abv$State %in% c(&quot;CO&quot;, &quot;MI&quot;, &quot;KY&quot;, &quot;IN&quot;, &quot;NY&quot;),]
par(mar=c(10,10,0,0)) #it&#39;s important to have that in a separate chunk

ggplot(data = hi_abv, aes(x = ABV * 100, fill = State, linetype = (State != &quot;CO&quot;), color = (State != &quot;CO&quot;))) +
  geom_density(alpha = 0.3, position=&quot;identity&quot;) +
    labs(x = &quot;Alcohol By Volume (%)&quot;, y = &quot;Density&quot;, title=&quot;Density of High-ABV \nBeers by State&quot;) +
  guides(color = &quot;none&quot;, linetype = &quot;none&quot;) +
  theme_wsj()+
  theme(axis.title=element_text(size=12))</code></pre>
<p><img src="BeersAndBreweries_files/figure-html/high_abv_states-1.png" width="672" /></p>
</div>
<div id="alcohol-by-volume" class="section level3">
<h3>Alcohol By Volume</h3>
<p>In this analysis, the distribution of Alcohol by Volume (ABV) in
2,410 beers was examined. The histogram of the ABV revealed a
right-skewed distribution, with the mean ABV of 5.97% and median of
5.60%.</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00100 0.05000 0.05600 0.05975 0.06700 0.12800</code></pre>
<p><img src="BeersAndBreweries_files/figure-html/abv_chart-1.png" width="672" /></p>
</div>
<div id="ibu" class="section level3">
<h3>IBU</h3>
<p>We see a similar trend happen when we discuss IBU for these beers as
well. The aptly named, “Bitter Bitch Imperial IPA” brings Oregon to the
top of the list, despite appearing to have fewer beers at the high end
of the IBU distribution.</p>
<pre><code>##                            Beer_Name State IBU
## 1857       Bitter Bitch Imperial IPA    OR 138
## 1719              Troopers Alley IPA    VA 135
## 1305                   Dead-Eye DIPA    MA 130
## 625  Bay of Bengal Double IPA (2014)    OH 126
## 425                     Abrasive Ale    MN 120
## 1452                    Heady Topper    VT 120</code></pre>
<p><img src="BeersAndBreweries_files/figure-html/high_ibu_states-1.png" width="672" /></p>
</div>
</div>
<div id="testing-the-correlation-between-ibu-and-abv"
class="section level2">
<h2>Testing the Correlation Between IBU and ABV</h2>
<p>As hinted to earlier, during the missing value imputation for ABV and
IBU, we noticed that the two columns seemed to be adequate predictors
for one another. The data indicates there is a strong positive
correlation between ABV and IBU at an r-value of 0.652 (r-values range
between -1.0 and 1.0):</p>
<pre><code>##       ABV               IBU        
##  Min.   :0.00100   Min.   :  4.00  
##  1st Qu.:0.05000   1st Qu.: 21.00  
##  Median :0.05600   Median : 35.00  
##  Mean   :0.05977   Mean   : 42.71  
##  3rd Qu.:0.06700   3rd Qu.: 64.00  
##  Max.   :0.12800   Max.   :138.00  
##  NA&#39;s   :62        NA&#39;s   :1005</code></pre>
<pre><code>## [1] 0.6523603</code></pre>
<p><img src="BeersAndBreweries_files/figure-html/ibu_abv_corr-1.png" width="672" /></p>
</div>
<div id="ipas-vs.-ales" class="section level2">
<h2>IPAs vs. Ales:</h2>
<div id="using-k-nearest-neighbors-to-predict-ipas-and-ales-from-ibuabv"
class="section level3">
<h3>Using K-Nearest Neighbors to Predict IPAs and Ales from IBU/ABV</h3>
<p>It was wondered whether there was a strong predictive factor that we
could use to test the hypothesis that IPAs tend to be more bitter and
have a higher alcohol content than other types of ales. In order to
perform this analysis, we first filtered out all non-ales from the data
set, then we used a predictive machine learning algorithm known as
K-nearest neighbors, which clumps beers together based on IBU and ABV,
and uses these clusters to predict whether a test beer is likely an IPA
or another type of ale.</p>
<p>From the model we built using the K-nearest neighbors approach, we
were able to predict with 79.6% accuracy whether a given ale was an IPA
or not.</p>
<p><img src="BeersAndBreweries_files/figure-html/knn-1.png" width="672" /></p>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction FALSE TRUE
##      FALSE   250   49
##      TRUE     45  116
##                                           
##                Accuracy : 0.7957          
##                  95% CI : (0.7559, 0.8316)
##     No Information Rate : 0.6413          
##     P-Value [Acc &gt; NIR] : 4.129e-13       
##                                           
##                   Kappa : 0.5534          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.757           
##                                           
##             Sensitivity : 0.8475          
##             Specificity : 0.7030          
##          Pos Pred Value : 0.8361          
##          Neg Pred Value : 0.7205          
##              Prevalence : 0.6413          
##          Detection Rate : 0.5435          
##    Detection Prevalence : 0.6500          
##       Balanced Accuracy : 0.7752          
##                                           
##        &#39;Positive&#39; Class : FALSE           
## </code></pre>
</div>
</div>
<div id="interesting-findings" class="section level2">
<h2>Interesting Findings:</h2>
<p>In this analysis, the relationship between Alcohol by Volume (ABV) in
beer produced by a state and the corresponding DUI arrest rate was
examined. A correlation was calculated between the two variables and the
results showed a negative correlation coefficient of -0.07, indicating
that there is no positive relationship between the two variables. This
suggests that producing beer with higher alcohol content does not
necessarily result in an increase in DUI arrests.</p>
<p><img src="BeersAndBreweries_files/figure-html/graph_findings-1.png" width="672" /></p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion:</h2>
<p>From our investigations, we raised a number of considerable questions
we were able to answer. We found that just five states accounted for 31%
of all breweries, with Colorado alone accounting for an impressive 8%.
We found there was a significant portion of the available beer data
which had not listed International Bitterness Units (IBU), opening the
field to furhter investigation and analysis. We found both the median
and mean Alcohol-by-Volume (ABV) metrics for American beers to rest
around 5.6%. And the data indicated there was a strongly predictive
factor (~79% accuracy) between IBU, ABV, and whether or not a beer would
be considered an Indian Pale Ale (IPA).</p>
<p>Outside of the initial topics proposed for investigation, we went out
of our way to gather relevant Driving Under the Influence (DUI)
statistics on a state basis. We compared these additional findings with
the data from the beers and breweries provided, and we found the data to
indicate that there was not a strong correlation between states that
produce high-ABV beers and number of DUI incidents. Although this may be
confounded by the fact that the beers produced in these states tend to
ship both domestically and abroad, we determined this should have an
overall positive impact on the marketing and sales division for these
more high-caliber products.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
